name: Node.js Package

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: yarn

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get base version
        id: get_version
        run: |
          BASE_VERSION=$(node -p "require('./package.json').version.split('-')[0]")
          echo "base_version=$BASE_VERSION" >> $GITHUB_OUTPUT

      - name: Get last pre-release number
        id: get_pre_number
        run: |
          LAST_VERSION=$(npm view . version 2>/dev/null || echo "${{ steps.get_version.outputs.base_version }}-0")
          if [[ "$LAST_VERSION" =~ -([0-9]+)$ ]]; then
            PRE_NUMBER=${BASH_REMATCH[1]}
          else
            PRE_NUMBER=0
          fi
          echo "pre_number=$PRE_NUMBER" >> $GITHUB_OUTPUT

      - name: Set new version and commit
        run: |
          NEW_PRE_NUMBER=$(( ${{ steps.get_pre_number.outputs.pre_number }} + 1 ))
          NEW_VERSION="${{ steps.get_version.outputs.base_version }}-$NEW_PRE_NUMBER"
          
          npm version "$NEW_VERSION" --no-git-tag-version
          
          git add package.json
          git commit -m "chore: bump version to $NEW_VERSION [skip ci]"
          git push

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
